pages/urls.py
from django import path

project/urls.py
from django.contrib import admin
from django.urls import path , include
from pages.views import homepage , switch , building_detail , custom_login , get_switches
from blocked_mac.views import Chek 
from mac_address.views import result 
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='home'),  # Define a URL pattern with the correct name
    path('search/', result, name='search_mac_address'),
    path('login/', custom_login, name="login"),
    path('switching/', switch, name="switch"),
    path('building/<int:building_id>/', building_detail, name='building_detail'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
    path('blocked_mac_address/', Chek , name="blocked_mac_address"),
    path('get_switches/', get_switches, name='get_switches'),
    path('api/', include('monitor.url')),
    path('acsess_point/', include('acsess_point.url')),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

acsess_point/models.py
from django.db import models
from pages.models import Building , Vlan
from cidrfield.models import IPNetworkField
from django.core.exceptions import ValidationError
from ipaddress import ip_network
# AccessPoint
class IpAdress(models.Model):
    ip_range = IPNetworkField(unique=True)
    building = models.OneToOneField(Building, on_delete=models.CASCADE, related_name='ip_address')

    def __str__(self):
        return f'{str(self.ip_range)} - {self.building}'

    def get_first_available_ip(self):
        network = ip_network(self.ip_range)
        used_ips = set(AccessPoint.objects.filter(
            building__ip_address=self).values_list('ip_address', flat=True))

        for ip in network.hosts():
            if str(ip) not in used_ips:
                return str(ip)

        raise ValidationError("No available IPs in the range")

class AccessPoint(models.Model):
    name = models.CharField(max_length=50)
    human_name = models.CharField(max_length=50)
    ip_address = models.GenericIPAddressField(unique=True, null=True, blank=True)
    vendor = models.CharField(max_length=50, default='default_vendor_name')
    description = models.TextField(blank=True, null=True)
    vlan = models.ForeignKey(Vlan, on_delete=models.CASCADE)
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    wifi_password = models.CharField(max_length=50 )
    admin_user = models.CharField(max_length=50  )
    admin_password = models.CharField(max_length=50  )
    mac_address = models.CharField(max_length=25, unique=True)
    port_status = models.CharField(max_length=10 , default='enable')
    real_port = models.CharField(max_length=10 , null=True , blank=True)
    switch_ip = models.GenericIPAddressField(null=True , blank=True)




    def save(self, *args, **kwargs):
        if not self.ip_address:
            if self.building and hasattr(self.building, 'ip_address'):
                self.ip_address = self.building.ip_address.get_first_available_ip()
            else:
                raise ValidationError("Building must have an associated IP range.")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.human_name} ({self.ip_address} - {self.id})"
    

    

templates/acsess_data.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link href="../static/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="../static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">

    <link href="../static/assets/css/style.css" rel="stylesheet">

 

 
  <style>
  

table {
        width: 1200px;
        height: 200px;
        border-collapse: collapse;
    }
    th, td {
        border: 1px solid black;
        padding: 8px;
        text-align: left;
    }
    
    th {
        background-color: #f1f1f1;
        width: 300px;
    }
/* Style for links to look like plain text */
.plain-link {
    background: none;
    border: none;
    padding: 0;
    margin: 0;
    font-size: 1em;
    color: blue;
    cursor: pointer;
    text-decoration: underline;
}


/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 15% auto; /* 15% from the top and centered */
  padding: 20px;
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}

</style>
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top header-inner-pages">
        <div class="container d-flex align-items-center">
            <div>
            <h2 style="margin-left: -285px; padding-left: 10px; font-size: 30px; color: rgb(238, 237, 238);">ASUH.SDN</h2>
        </div>

            <nav id="navbar" class="navbar" style="text-align: center; padding-left: 1030px;">
                <ul >
                    <li><a class="nav-link scrollto active" href="/" style="font-size: 17px;" >Home</a></li>
                    <li><a href="/search" style="font-size: 17px;" >Search</a></li> 
                    <li><a class="nav-link scrollto" style="font-size: 17px;" href="/switching/">Switches</a></li>
                    <li><a class="nav-link scrollto" style="font-size: 17px;" href="/acsess_point/">Access Point</a></li>
                    
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <li>  <button class="getstarted scrollto" type="submit">Logout</button></li>
                    </form>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
                
            </nav>
            <!-- .navbar -->
          
        </div>
    
        
    </header>
    <!-- End Header -->

    <main id="main">
        <section id="breadcrumbs" class="breadcrumbs">
            <div class="container" style="display: flex; justify-content: space-between; align-items: center; padding: 5px; margin: 10px;">
        
                <!-- Logo container -->
                <div style="width: 100px; height: 100px; margin-top: 0; padding-top: 0;">
                    <img src="../static/images/asuh-removebg-preview.png" alt="" style="width: 100%; height: auto;">
                </div>  
                    </div>
        </section>
        
        <div style="padding-left: 350px; font-size: 20px; font-weight: bold;display: grid; ">
            <h1>Access Point Details</h1>
            <table>
                <tr>
                    <th>IP</th>
                    <td>{{ acsess.ip_address }}</td>

                </tr>
                <tr>
                    <th>MAC address</th>
                    <td>{{ acsess.mac_address }}</td>
                </tr>
                <tr>
                    <th>admin user</th>
                    <td>{{ acsess.admin_user }}</td>

                </tr>
                <tr>
                    <th>admin password</th>
                    <td>{{ acsess.admin_password }}</td>
                </tr>

                <tr>
                    <th>vendor</th>
                    <td>{{ acsess.vendor }}</td>

                </tr>
               
                <tr>
                    <th>vlan</th>
                    <td>{{ acsess.vlan }}</td>

                </tr>
                <tr>
                    <th > port status </th>
                    <td>{{ acsess.port_status }}</td>
    
                </tr>   
                <tr>
                    <th>Wifi name</th>
                    <td>{{ acsess.name }}</td>
                </tr>
                <tr>
                    <th>wifi password</th>
                    <td>{{ acsess.wifi_password }}</td>

                </tr>
                
                    <th>human_name</th>
                    <td>{{ acsess.human_name }}</td>
            
                </tr>
                <tr>
                    <th>Building</th>
                    <td>{{ acsess.building }}</td>

                </tr>
                    <tr>
                    <th>description</th>
                    <td>{{ acsess.description }}</td>

                </tr>
           
                    
            </table>
    
        </div>
        
        <div style="padding-top: 50px; display: flex; justify-content: center; align-items: center; flex-direction: column;">
            {% if mac_data.device_ip %}
            <form method="post" action="" style="display: flex; justify-content: center; margin-bottom: 20px;">
                {% csrf_token %}
                <button name="action" value="Block in core" class="inline-button" style="background-color: rgb(223, 166, 166); margin-right: 10px;">Block in core</button>
                {%if acsess.port_status == 'enable'%}
                <button name="action" value="shutdown port" class="inline-button" style="background-color: rgb(223, 166, 166); margin-right: 10px;">shutdown port</button>
                {%else%}
                <button name="action" value="no shutdown port" class="inline-button" style="background-color: rgba(55, 68, 90, 0.9); margin-right: 10px;">no shutdown port</button>
                {% endif %}
                <button type="button" onclick="showVlanInput()" class="inline-button" style="background-color: rgba(55, 68, 90, 0.9); margin-right: 10px;">Assign to VLAN</button>
                <button name="action" value="Show MAC Address" style="background-color: rgba(55, 68, 90, 0.9);">Show MAC Address</button>
            </form>
            <div id="vlanInput" style="display: none; margin-top: 10px;">
                <form method="post" action="" style="display: flex; justify-content: center;">
                    {% csrf_token %}
                    <input type="text" name="vlan_number" placeholder="Enter VLAN Number">
                    <button type="submit" name="action" value="Assign to VLAN">Submit</button>
                </form>
            </div>
            {% else %}
            <form method="post" action="" style="display: flex; justify-content: center; margin-bottom: 20px;">
                {% csrf_token %}
                <button name="action" value="Block in core" class="inline-button" style="background-color: rgb(223, 166, 166);">Block in core</button>
            </form>
            {% endif %}
            {% if not display %}
            <form method="post" action="" style="display: flex; justify-content: center;">
                {% csrf_token %}
                <button name="action" value="take data" class="inline-button" style="background-color: rgba(55, 68, 90, 0.9);">take data</button>
            </form>
            {% endif %}
        </div>
        
        <div style="padding-left: 100px; padding-top: 50px;">
            {% if mac_table %}
            <h2 style="text-align: center;">The MAC address table for {{ acsess.name }} is</h2>
            <table style="width: 60%;height: 50%; margin: auto;">
                <tr>
                    <th style=" text-align: center;">VLAN</th>
                    <th style=" text-align: center;">MAC Address</th>
                    <th style=" text-align: center;">Type</th>
                    <th style=" text-align: center;">Port</th>
                </tr>
                {% for entry in mac_table %}
                <tr>
                    <td style=" text-align: center;">{{ entry.vlan }}</td>
                    <td style=" text-align: center;">{{ entry.mac_address }}</td>
                    <td style=" text-align: center;">{{ entry.type }}</td>
                    <td style=" text-align: center;">{{ entry.port }}</td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}
        </div>
        
        
    </main>
    <!-- End #main -->


    <!-- ======= Footer ======= -->
    <div style="padding-top: 250px;">
        <footer id="footer" style="position: relative;
        left: 0;
        bottom: 0;
        width: 100%;
        height: 60px; /* Adjust to your footer's height */
        ">
            <div class="container footer-bottom clearfix">
                <div class="copyright">
                    &copy;<strong><span>Eng: Moustafa Mohamed</span></strong>
                </div>
                <div class="credits">
                    
                </div>
            </div>
        </footer>
    </div> 
    <!-- End Footer -->

    <script src="../static/assets/vendor/aos/aos.js "></script>
    <script src="../static/assets/vendor/glightbox/js/glightbox.min.js "></script>
    <script src="../static/assets/vendor/swiper/swiper-bundle.min.js "></script>
 
    <!-- Template Main JS File -->
    <script src="../static/assets/js/main.js "></script>
    
    <script>
        function showVlanInput() {
            var vlanInput = document.getElementById('vlanInput');
            vlanInput.style.display = 'block';
        }
    </script>
    
        
</body>

</html>

templates/add_all.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link href="../static/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="../static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">

    <link href="../static/assets/css/style.css" rel="stylesheet">

 
  <style>
    
    /* ... (existing styles) ... */
    
    .switch-navbar, .switch-box {
    display: grid;
    grid-template-columns: repeat(5, minmax(120px, 1fr)); /* Adjust based on your content */
    gap: 1em;
}

.switch-navbar > div, .switch-box > div {
    text-align: left; /* Align text to the left */
}

/* Style for links to look like plain text */
.plain-link {
    background: none;
    border: none;
    padding: 0;
    margin: 0;
    font-size: 1em;
    color: blue;
    cursor: pointer;
    text-decoration: underline;
}
.status-up{
    color: rgb(3, 168, 3);
}
.status-down{
    color: rgb(255, 0, 0);
}
/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 15% auto; /* 15% from the top and centered */
  padding: 20px;
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}

</style>
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top header-inner-pages">
        <div class="container d-flex align-items-center">
            <div>
            <h2 style="margin-left: -285px; padding-left: 10px; font-size: 30px; color: rgb(238, 237, 238);">ASUH.SDN</h2>
        </div>

            <nav id="navbar" class="navbar" style="text-align: center; padding-left: 1030px;">
                <ul >
                    <li><a class="nav-link scrollto active" href="/" style="font-size: 17px;" >Home</a></li>
                    <li><a href="/search" style="font-size: 17px;" >Search</a></li> 
                    <li><a class="nav-link scrollto" style="font-size: 17px;" href="/switching/">Switches</a></li>
                    <li><a class="nav-link scrollto" style="font-size: 17px;" href="/acsess_point/">Access Point</a></li>
                    
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <li>  <button class="getstarted scrollto" type="submit">Logout</button></li>
                    </form>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
                
            </nav>
            <!-- .navbar -->
          
        </div>
    
        
    </header>
    <!-- End Header -->

    <main id="main">
<!--  -->

<section id="breadcrumbs" class="breadcrumbs">
    <div class="container" style="display: flex; justify-content: space-between; align-items: center; padding: 5px; margin: 10px;">

        <!-- Logo container -->
        <div style="width: 100px; height: 100px; margin-top: 0; padding-top: 0;">
            <img src="../static/images/asuh-removebg-preview.png" alt="" style="width: 100%; height: auto;">
        </div>  

        <!-- Button -->
        <div style="flex-grow: 1; padding-left: 450px;">
            <button style="background-color: rgba(40, 58, 90, 0.9); font-size: 20px;" onclick="toggleAllSwitches()">Toggle All Switches</button>
        </div>
    </div>
</section>

        
        
        
        
        <!-- <div style=" position: relative; ">    
           
        </div> -->
        <!-- End Breadcrumbs -->
        
        
        
        <!-- Trigger/Open The Modal -->
        <button id="myBtn"style="background-color: rgba(40, 58, 90, 0.9);">Add Access Point</button>

        <!-- Buildings and Switches -->
        {% for item in buildings %}
       <!-- ... existing code ... -->

      
<!-- ... existing code ... -->
<div class="switch-summary" style="padding-left: 250px;">
    <!-- The Modal -->
    <div id="myModal" class="modal">
    
        <!-- Modal content -->
        <div class="modal-content">
          <span class="close">&times;</span>
          <form method="post">
              {% csrf_token %}
              {{ access_point_form.as_p }}
              <button type="submit" name="submit_access_point">Save Access Point</button>
          </form>
        </div>
      
      </div>
      
</div>
        
    <div style="padding-top: 30px; padding-left: 10px;" class="building"> <!-- Reduced padding-bottom -->
        <div class="switch-box"> 
            <div>
                
                <a href="#" class="plain-link" style="color: rgb(255, 255, 255); font-weight: bold; background-color: rgba(40, 58, 90, 0.9); display: block; width: 200px; text-align: center; padding: 10px; border-radius: 100px; font-size: 20px; " onclick="event.preventDefault(); toggleSwitches('switches-{{ item.id }}')">{{ item.name }}</a>
                <hr style="width: 470%; margin: 20px auto;">
                
            </div> 
            
        
            <!-- ... other switch-box divs ... -->
        </div>
        
        
        <!-- ... -->
    </div>
    <div id="switches-{{ item.id }}" class="switches" style="display: none; font-weight: bold;">
        <div id="switch-navbar" class="switch-navbar" style="padding-left: 250px; font-size: 20px; font-weight: bold; color: rgb(107, 170, 230); ">
            <div>Wifi name</div>
            <div>IP Address</div>
            <div>Vendor</div>
            <div>Mac address</div>
            <div>connection</div>
            
        </div>
        
        <hr style="width: 80%; margin: 20px auto; "> 
        {% for access_point in item.accesspoint_set.all %}
            <div class="switch-box" style="padding-left: 250px; margin-bottom: 20px; color: rgba(40, 58, 90, 0.9);"> <!-- Added margin-bottom -->
                <div>{{ access_point.name }}</div>
                <div>{{ access_point.ip_address }}</div>
                <div>{{ access_point.vendor }}</div>
                <div>{{ access_point.mac_address }}</div>
                <div><a href="{% url 'access_point' access_point.id %}">more details</a></div>
            </div>
            {% if not forloop.last %} <!-- Check if it's not the last item in the loop -->
                <hr style="width: 80%; margin: 20px auto;"> <!-- Horizontal line as a separator -->
            {% endif %}
            
        {% endfor %}
        <hr style="width: 80%; margin: 20px auto;"> 
        
    </div>
    
            </div>
        </div>
        {% endfor %}

    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
    <div >
        <footer id="footer" style="position: relative;
        left: 0;
        bottom: 0;
        width: 100%;
        height: 60px; /* Adjust to your footer's height */
        ">
            <div class="container footer-bottom clearfix">
                <div class="copyright">
                    &copy;<strong><span> Eng: Moustafa Mohamed</span></strong>
                </div>
                <div class="credits">
                    
                </div>
            </div>
        </footer>
    </div> 
    <!-- End Footer -->

   
    <script src="../static/assets/vendor/aos/aos.js "></script>
    <script src="../static/assets/vendor/glightbox/js/glightbox.min.js "></script>
    <script src="../static/assets/vendor/swiper/swiper-bundle.min.js "></script>
 
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function () {
            var searchForm = document.getElementById('search-form');
            searchForm.addEventListener('submit', function() {
                document.getElementById('loader').style.display = 'block';
            });
        });
    </script>
    <script>
 function toggleSwitches(id) {
    var switches = document.getElementById(id);

    if (switches.style.display === "none" || switches.style.display === "") {
        switches.style.display = "block";
    } else {
        switches.style.display = "none";
    }
}



    
function toggleAllSwitches() {
    var allSwitches = document.getElementsByClassName('switches');
    for (var i = 0; i < allSwitches.length; i++) {
        var switches = allSwitches[i];

        if (switches.style.display === "none" || switches.style.display === "") {
            switches.style.display = "block";
        } else {
            switches.style.display = "none";
        }
    }
}


    </script>
    <script>
        // Get the modal
        var modal = document.getElementById("myModal");
        
        // Get the button that opens the modal
        var btn = document.getElementById("myBtn");
        
        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];
        
        // When the user clicks the button, open the modal 
        btn.onclick = function() {
          modal.style.display = "block";
        }
        
        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
          modal.style.display = "none";
        }
        
        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }
        </script>
        
</body>

</html>

templates/blocked_mac_address.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>Blocked_Mac_Address</title>
    <link rel="stylesheet" href="{% static 'switching.css'%}">
    <link rel="stylesheet" href="{% static 'home.css' %} ">
</head>

<body>
    <nav>
        <ul>
            <li style="margin-top: 20px;"><a href="/">Home</a></li>
            <li style="margin-top: 20px;"><a href="/switching">switching</a></li>
            <li style="margin-top: 20px;"><a href="/search">Search</a></li>
            <li style="margin-top: 20px;"><a href="#">services</a></li>
        </ul>
    </nav>
 

    {% block content %}
    <form method="post">
        {% csrf_token %}
        
        <!-- Button for Core Block -->
        <button type="submit" name="action" value="core_block">Check Core Block</button>

        <!-- Button for All Block -->
        <button type="submit" name="action" value="all_block">Check All Block</button>

        <!-- Button for Getting MAC Address Table -->
        <button type="submit" name="action" value="git_mac">Get MAC Address Table</button>
        <!-- Button for backup -->
        <button type="submit" name="action" value="backup">Get backup</button>
        <!-- Button for migration -->
        <button type="submit" name="action" value="migration">migration</button>
    </form>
{% endblock %}

    
        </div>

    <script src="{% static 'switching.js'%}"></script>
</body>

</html>

templates/lgin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <style>
        body {
            background-size: cover;
            background-image: url("{% static 'images/po.jpg' %}");

            transition: background-image 100s ease-in-out;
        }
      
    </style>    
</head>

<body style="padding-top: 220px; ">
    <div class="wrapper" >
                       
        <div class="logo1">
            
            <img style="width: 100px;" src="../static/images/asuh-removebg-preview.png" >
        </div>
        <div class="text-center mt-4 name">
           <h4 style="margin-top: 10px;"> ASUH SDN Solution</h4>
        </div>
        
        <form class="p-3 mt-3"  method="post" action="" >
            {% csrf_token %}
            <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                <label for="username">Username</label>
                <input type="text" name="username" id="userName" placeholder="Username" required>
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                <label for="password">Password</label>
                <input type="password" name="password" id="pwd" placeholder="Password" required>
            </div>
            <button type="submit" id="myButton" class="btn1 btn mt-3">Login</button>
        </form>
        
    </div>
     <!-- Hidden element for error message -->
     <div id="error-message" data-error="{% if error_message %}{{ error_message }}{% endif %}" style="display:none;"></div>
    </div>

    <script>
        var backgroundImageArray = [
            "{% static 'images/po.jpg' %}",
            "{% static 'images/1398865.jpg' %}",
            "{% static 'images/im4.jpg' %}"
        ];

        function changeBackgroundImage() {
            var randomIndex = Math.floor(Math.random() * backgroundImageArray.length);
            var selectedImage = backgroundImageArray[randomIndex];
            document.body.style.backgroundImage = 'url(' + selectedImage + ')';
        }

       
    </script>
    <script>
         function displayErrorMessage() {
            var errorMessageElement = document.getElementById('error-message');
            var errorMessage = errorMessageElement.getAttribute('data-error');
            if (errorMessage) {
                window.alert(errorMessage);
            }
        }

        window.onload = function() {
            changeBackgroundImage();
            displayErrorMessage();
        };
    </script>
</body>
</html>